---
- hosts: mapreduce-workers
  remote_user: root
  tasks:
    - name: Provision hadoop user
      user: name=hadoop
    - name: Create some tmp nodes
      command: mkdir -p /scratch/tmp0
    - name: Ensure spark is not running
      shell: ps x | grep Spark | grep -v grep || true
    - name: Assign scratch partitions to hadoop user
      shell: chown -R hadoop /scratch/tmp*
    - name: Provision mapred-site.xml
      template: src=templates/mapred-site.xml-mapreduce dest=/opt/mapr/conf/mapred-site.xml
    - name: Start Map-Reduce TaskTracker
      command: echo /opt/mapr/bin/tt_start.sh
      # NOTE: Can not seem to notify to a different node ...
#      notify:
#        - restart JobTracker
#  handlers:
#    - name: restart JobTracker
#      shell: while [ `echo $(( RANDOM%12 ))` -ne 0 ]; do sleep 1; echo -n .; done && echo /opt/mapr/bin/jb_stop.sh && echo /opt/mapr/bin/jb_start.sh
